### ISSUE TITLE
Types do not support additional properties

### ISSUE THREAD

**Issue by vromero** [mulesoft-labs/raml-java-tools#31]
I've seen some code JAXRS related but bare conversion to POJO does not seem to support additional properties. The following type:

```
types:
  salutation:
    type: object
    additionalProperties: true
```

Will generate the following POJO:

```
public interface Salutation {
}
```
```
public class SalutationImpl implements Salutation {
}
```

I'm also attaching a project to replicate: [additionalProperties.tar.gz](https://github.com/mulesoft-labs/raml-java-tools/files/3446671/additionalProperties.tar.gz)
