### ISSUE TITLE
Support pattern properties

### ISSUE THREAD

**Issue by jpbelang** [mulesoft-labs/raml-java-tools#7]
```yaml
#%RAML 1.0
title: My API With Types
types:
  Person:
    properties:
      name:
        required: true
        type: string
      age:
        required: false
        type: number
      /somepattern/: # force all additional properties to be a string
        type: string
```

I have to check that jackson supports this (I think it does).
I have to support the additionalProperties facet correctly. (I always set to true now).
